"""Outputs: CDSA-format Markdown report, self-contained HTML timeline, ATT&CK Navigator layer."""
from __future__ import annotations

import html
import ipaddress
import json
from datetime import datetime, timezone

from .correlate import Chain


def _ts(dt) -> str:
    return dt.strftime("%Y-%m-%d %H:%M:%S UTC")


def _ioc_type(value: str) -> str:
    try:
        ipaddress.ip_address(value)
        return "IP Address"
    except ValueError:
        pass
    if "\\" in value or value.lower().endswith(".exe"):
        return "Process"
    if value.upper().startswith("CN="):
        return "Directory Object"
    return "Workstation/Domain"


# ---------- Markdown (CDSA commercial format) ----------

def markdown_report(chains: list[Chain], title: str = "Security Incident Report") -> str:
    now = datetime.now(timezone.utc)
    out = [f"# {title}", f"_Generated by ChainHunter on {_ts(now)}_", ""]
    if not chains:
        return "\n".join(out + ["No detections."])

    for n, c in enumerate(chains, 1):
        ents = c.entities
        out += [
            f"## Incident {n} — Severity: {c.severity} (score {c.score})",
            "",
            "### Executive Summary",
            "#### Incident Overview",
            f"Between {_ts(c.start)} and {_ts(c.end)}, ChainHunter correlated {len(c.detections)} "
            f"detections across {len(ents['hosts'])} host(s) into a single attack chain spanning the "
            f"following kill-chain phases: **{' → '.join(c.phases)}**.",
            "",
            "#### Key Findings",
        ]
        for d in c.detections:
            out.append(f"- {_ts(d.time)} — **{d.rule.title}** on `{d.host}` "
                       f"(actor `{d.actor or 'n/a'}`, source `{d.source or 'n/a'}`)")
        out += [
            "",
            "#### Immediate Actions",
            "- _Analyst to complete: containment, credential resets, host isolation._",
            "",
            "#### Stakeholder Impact",
            "- _Analyst to complete: affected business services, data, and users._",
            "",
            "### Technical Analysis",
            "#### Affected Systems & Data",
            f"- Hosts: {', '.join(sorted(ents['hosts'])) or 'n/a'}",
            f"- Accounts: {', '.join(sorted(ents['accounts'])) or 'n/a'}",
        ]
        if ents.get("targeted"):
            out.append(f"- Targeted accounts: {', '.join(sorted(ents['targeted']))}")
        out += ["", "#### Evidence Sources & Analysis", ""]

        for step, d in enumerate(c.detections, 1):
            q = d.rule.meta.get("queries", {})
            out += [f"##### Step {step} — {d.rule.title}",
                    f"**Objective:** {d.rule.description}", ""]
            for lang in ("kql", "spl", "eql"):
                if q.get(lang):
                    out += [f"```{lang}", q[lang].strip(), "```"]
            out += [
                "",
                f"_Figure {n}.{step} - {d.rule.title} evidence (attach screenshot)_",
                "",
                f"**Finding:** {len(d.events)} matching event(s) from {_ts(d.time)} to {_ts(d.end)} "
                f"on `{d.host}`; actor `{d.actor or 'n/a'}`, source `{d.source or 'n/a'}`.",
                "",
                f"**Kill Chain Phase:** {d.rule.meta.get('kill_chain', 'Unknown')} · "
                f"**MITRE ATT&CK:** {', '.join(d.rule.attack_ids) or 'n/a'}",
                "",
            ]

        out += ["### Indicators of Compromise", "", "| Type | Value | Context |", "|---|---|---|"]
        for s in sorted(ents["sources"]):
            out.append(f"| {_ioc_type(s)} | `{s}` | Origin of malicious activity |")
        for a in sorted(ents["accounts"]):
            out.append(f"| Account | `{a}` | Used during intrusion |")
        for h in sorted(ents["hosts"]):
            out.append(f"| Host | `{h}` | Affected system |")

        out += ["", "### Appendix: Technical Timeline", "",
                "| Time (UTC) | Host | Event | Phase | ATT&CK |", "|---|---|---|---|---|"]
        for d in c.detections:
            out.append(f"| {_ts(d.time)} | {d.host} | {d.rule.title} | "
                       f"{d.rule.meta.get('kill_chain', '')} | {', '.join(d.rule.attack_ids)} |")
        out.append("")
    return "\n".join(out)


# ---------- HTML timeline ----------

_CSS = """
:root{--bg:#f7f7f5;--fg:#1d1d1b;--muted:#6b6b66;--card:#fff;--line:#e2e2dc;--accent:#b4232a}
@media (prefers-color-scheme:dark){:root{--bg:#141413;--fg:#ecebe6;--muted:#9b9a93;--card:#1e1e1c;--line:#34332f;--accent:#ff6b6b}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.5 system-ui,sans-serif}
main{max-width:960px;margin:0 auto;padding:24px 16px}h1{margin:0 0 4px}.muted{color:var(--muted)}
.chain{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:16px;margin:20px 0}
.phases{display:flex;flex-wrap:wrap;gap:6px;margin:8px 0 12px}.phase{border:1px solid var(--line);border-radius:999px;padding:2px 10px;font-size:13px}
.ev{display:grid;grid-template-columns:170px 1fr;gap:12px;padding:10px 0;border-top:1px solid var(--line)}
.ev b{display:block}.sev{color:var(--accent);font-weight:600}code{font-size:13px}
@media (max-width:600px){.ev{grid-template-columns:1fr;gap:2px}}
"""


def html_report(chains: list[Chain]) -> str:
    e = html.escape
    parts = [f"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' "
             f"content='width=device-width,initial-scale=1'><title>ChainHunter Timeline</title>"
             f"<style>{_CSS}</style></head><body><main><h1>ChainHunter</h1>"
             f"<p class='muted'>{len(chains)} correlated attack chain(s)</p>"]
    for n, c in enumerate(chains, 1):
        parts.append(f"<section class='chain'><h2>Incident {n} <span class='sev'>{c.severity}</span></h2>"
                     f"<div class='muted'>{e(_ts(c.start))} → {e(_ts(c.end))}</div><div class='phases'>")
        parts += [f"<span class='phase'>{e(p)}</span>" for p in c.phases]
        parts.append("</div>")
        for d in c.detections:
            parts.append(
                f"<div class='ev'><div class='muted'>{e(_ts(d.time))}</div><div><b>{e(d.rule.title)}</b>"
                f"<code>{e(d.host)}</code> · actor <code>{e(d.actor or 'n/a')}</code> · "
                f"source <code>{e(d.source or 'n/a')}</code><div class='muted'>"
                f"{e(d.rule.meta.get('kill_chain', ''))} · {e(', '.join(d.rule.attack_ids))} · "
                f"{len(d.events)} event(s)</div></div></div>")
        parts.append("</section>")
    parts.append("</main></body></html>")
    return "".join(parts)


# ---------- ATT&CK Navigator layer ----------

def navigator_layer(chains: list[Chain]) -> str:
    counts: dict[str, int] = {}
    for c in chains:
        for d in c.detections:
            for t in d.rule.attack_ids:
                counts[t] = counts.get(t, 0) + 1
    layer = {
        "name": "ChainHunter detections",
        "versions": {"layer": "4.5", "navigator": "4.9.1", "attack": "15"},
        "domain": "enterprise-attack",
        "techniques": [{"techniqueID": t, "score": n, "comment": f"{n} detection(s)"}
                       for t, n in sorted(counts.items())],
        "gradient": {"colors": ["#fde0dd", "#b4232a"], "minValue": 0, "maxValue": max(counts.values(), default=1)},
    }
    return json.dumps(layer, indent=2)
