"""Outputs: CDSA-format Markdown report, interactive HTML (attack graph + timeline + evidence),
ATT&CK Navigator layer, and machine-readable JSON for SOAR/ticketing hand-off."""
from __future__ import annotations

import html
import ipaddress
import json
from datetime import datetime, timezone

from .convert import queries_for
from .correlate import ALERT_LEVELS, Chain, risk_of
from .detect import Detection, Rule
from .sequence import norm_entity
from .story import AlertGroup, group_alerts, process_index, process_tree, short_host, show, swimlane


def _ts(dt) -> str:
    return dt.strftime("%Y-%m-%d %H:%M:%S UTC")


def _ioc_type(value: str) -> str:
    try:
        ipaddress.ip_address(value)
        return "IP Address"
    except ValueError:
        pass
    if "\\" in value or value.lower().endswith(".exe"):
        return "Process"
    if value.upper().startswith("CN="):
        return "Directory Object"
    return "Workstation/Domain"


def _queries(d: Detection, registry: dict[str, Rule]) -> dict[str, str]:
    return d.extra.get("queries") or queries_for(d.rule, registry)


def _kind_label(d: Detection) -> str:
    return {"sequence": " [SEQUENCE]", "anomaly": " [ANOMALY]"}.get(d.rule.kind, "")


# ---------- Markdown (CDSA commercial format) ----------

def markdown_report(chains: list[Chain], registry: dict[str, Rule], title: str = "Security Incident Report") -> str:
    out = [f"# {title}", f"_Generated by ChainHunter on {_ts(datetime.now(timezone.utc))}_", ""]
    if not chains:
        return "\n".join(out + ["No detections."])

    for n, c in enumerate(chains, 1):
        ents = c.entities
        seqs = [d for d in c.detections if d.rule.kind == "sequence"]
        out += [
            f"## Incident {n} — Severity: {c.severity} (score {c.score})",
            f"**Confidence:** {c.confidence}  ",
            f"**Window:** {_ts(c.start)} → {_ts(c.end)}  ",
            f"**ATT&CK:** {', '.join(c.techniques)}",
            "",
            "### Executive Summary",
            "#### Incident Overview",
            f"Between {_ts(c.start)} and {_ts(c.end)}, ChainHunter correlated {len(c.detections)} detections "
            f"across {len(ents['hosts'])} host(s) and {len(ents['accounts'])} account(s) into one attack chain "
            f"progressing through **{' → '.join(c.phases)}**.",
        ]
        if seqs:
            out.append(f"{len(seqs)} multi-stage sequence rule(s) confirmed ordered attacker activity, "
                       f"raising confidence that this is a single coordinated intrusion rather than unrelated alerts.")
        groups = group_alerts(c)
        story = [g for g in groups if g.level in ALERT_LEVELS] or groups
        context = [g for g in groups if g not in story]
        out += ["", "#### Key Findings"]
        for g in story:
            d = g.detections[0]
            out.append(f"- {_ts(g.first)} — **{g.rule.title}**{_kind_label(d)} on `{short_host(g.host) or 'n/a'}`"
                       f"{f' (×{g.count})' if g.count > 1 else ''} — {g.level}")
        flagged = [r for r in c.risk if r.flagged]
        out += ["", "#### Immediate Actions"]
        for r in flagged:
            action = {"Account": "Disable / reset credentials (twice for krbtgt if replication abuse is confirmed)",
                      "Source": "Block at perimeter/EDR and hunt for further activity",
                      "Host": "Isolate and acquire memory + disk for forensics"}[r.kind]
            out.append(f"- {r.kind} `{r.value}` — {action}.")
        out += ["- _Analyst to confirm and extend._", "", "#### Stakeholder Impact",
                "- _Analyst to complete: affected business services, data, and users._", ""]

        out += ["### Risk-Based Alerting — Entity Risk", "",
                "| Entity | Type | Risk | Techniques | Phases | Flagged |", "|---|---|---|---|---|---|"]
        for r in c.risk[:12]:
            out.append(f"| `{r.value}` | {r.kind} | {r.score} | {', '.join(sorted(r.techniques))} | "
                       f"{len(r.phases)} | {'**YES**' if r.flagged else 'no'} |")

        out += ["", "### Technical Analysis", "#### Affected Systems & Data",
                f"- Hosts: {', '.join(sorted(ents['hosts'])) or 'n/a'}",
                f"- Accounts: {', '.join(sorted(ents['accounts'])) or 'n/a'}"]
        if ents.get("targeted"):
            out.append(f"- Targeted accounts: {', '.join(sorted(ents['targeted']))}")
        out += ["", "#### Evidence Sources & Analysis", ""]

        for step, g in enumerate(story, 1):
            d = g.detections[0]
            out += [f"##### Step {step} — {d.rule.title}{_kind_label(d)}", f"**Objective:** {d.rule.description}", ""]
            if d.rule.kind == "sequence":
                out.append("**Sequence stages:**")
                for sid, sd in d.extra["steps"]:
                    out.append(f"1. `{sid}` — {_ts(sd.time)} · {sd.rule.title} · actor `{sd.actor or 'n/a'}` on `{sd.host or 'n/a'}`")
                out.append("")
            for lang, q in _queries(d, registry).items():
                out += [f"```{lang}", q, "```"]
            detail = ""
            if d.rule.kind == "anomaly":
                detail = " " + ", ".join(f"{k}={v}" for k, v in d.extra.items() if k != "queries")
            out += ["", f"_Figure {n}.{step} - {d.rule.title} evidence (attach screenshot)_", "",
                    f"**Finding:** {g.count} detection(s), {len(g.events)} event(s) from {_ts(g.first)} to {_ts(g.last)} "
                    f"on `{g.host or 'n/a'}`; actor(s) `{', '.join(show(a) for a in g.actors[:5]) or 'n/a'}`.{detail}", "",
                    f"**Kill Chain Phase:** {d.rule.meta.get('kill_chain', 'Unknown')} · "
                    f"**MITRE ATT&CK:** {', '.join(d.rule.attack_ids) or 'n/a'}", ""]
        if context:
            out += ["#### Low / informational context", "", "| First seen | Alert | Host | Count |", "|---|---|---|---|"]
            out += [f"| {_ts(g.first)} | {g.rule.title} | {short_host(g.host)} | {g.count} |" for g in context]
            out.append("")

        out += ["### Indicators of Compromise", "", "| Type | Value | Context |", "|---|---|---|"]
        out += [f"| {_ioc_type(s)} | `{s}` | Origin of malicious activity |" for s in sorted(ents["sources"])]
        out += [f"| Account | `{a}` | Used during intrusion |" for a in sorted(ents["accounts"])]
        out += [f"| Host | `{h}` | Affected system |" for h in sorted(ents["hosts"])]
        out += ["", "### Appendix: Technical Timeline", "",
                "| First seen (UTC) | Host | Alert | Count | Phase | ATT&CK |", "|---|---|---|---|---|---|"]
        for g in story:
            out.append(f"| {_ts(g.first)} | {short_host(g.host)} | {g.rule.title}{_kind_label(g.detections[0])} | "
                       f"{g.count} | {g.rule.meta.get('kill_chain', '')} | {', '.join(g.rule.attack_ids)} |")
        out.append("")
    return "\n".join(out)


# ---------- HTML (attack graph + timeline + evidence) ----------

_CSS = """
:root{--bg:#f6f5f1;--fg:#1c1b19;--muted:#6c6a63;--card:#fff;--line:#e3e1da;--accent:#b4232a;
--src:#b4232a;--acct:#a15c00;--host:#1f5fa8;--seq:#6b3fa0;--chip:#f0eee8;
--crit:#b4232a;--high:#d9480f;--med:#b58100;--low:#9c9a92;--hit:#fdf0ec}
@media (prefers-color-scheme:dark){:root:not([data-theme=light]){--bg:#131312;--fg:#ebe9e3;--muted:#9c9a92;
--card:#1d1c1a;--line:#33322e;--accent:#ff6b6b;--src:#ff6b6b;--acct:#f0a53a;--host:#6aa5ff;--seq:#b48cf0;--chip:#262522;
--crit:#ff5c5c;--high:#ff8c42;--med:#e6b422;--low:#6c6a63;--hit:#2b1d1a}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.5 system-ui,-apple-system,sans-serif}
main{max-width:1440px;margin:0 auto;padding:28px 24px 64px}h1{margin:0;font-size:28px}h2{margin:0 0 4px;font-size:22px}
h4{margin:14px 0 4px;font-size:14px}
svg.lane{width:100%;height:auto;border:1px solid var(--line);border-radius:10px;background:var(--bg)}
.lanebg{fill:var(--chip)}.lanelbl{fill:var(--fg);font-size:13px;font-weight:600}.tick{stroke:var(--line)}
.ticklbl{fill:var(--muted);font-size:11px}.hop{stroke:var(--accent);stroke-width:1.5;stroke-dasharray:3 3}
.hoplbl{fill:var(--accent);font-size:11px}circle{stroke:var(--bg);stroke-width:1}
.grid2{display:grid;grid-template-columns:3fr 2fr;gap:20px;align-items:start}
@media (max-width:1000px){.grid2{grid-template-columns:1fr}}
.ptree,.ptree ul{list-style:none;margin:0;padding-left:22px;border-left:1px dashed var(--line)}
.ptree{padding-left:6px;border:0}.proc{padding:6px 10px;margin:4px 0;border-radius:8px;border:1px solid var(--line);background:var(--card)}
.proc.hit{background:var(--hit);border-color:var(--accent)}.cmd{font:12px/1.4 ui-monospace,Consolas,monospace;color:var(--muted);word-break:break-all}
.badge{display:inline-block;font-size:11px;font-weight:600;border-radius:4px;padding:0 6px;margin:2px 0 0 6px;color:#fff}
.badge.critical{background:var(--crit)}.badge.high{background:var(--high)}.badge.medium{background:var(--med)}
.badge.low,.badge.informational{background:var(--low)}
.filters{display:flex;flex-wrap:wrap;gap:14px;align-items:center;margin:8px 0 10px;font-size:14px}
.filters input[type=search],.filters select{font:inherit;padding:5px 9px;border-radius:7px;border:1px solid var(--line);background:var(--card);color:var(--fg)}
.ai{border:1px solid var(--line);border-radius:10px;padding:4px 16px 10px;background:var(--card)}
.ai li{margin:4px 0}.ai li.bad{color:var(--muted)}.cite{font:12px ui-monospace,Consolas,monospace;color:var(--host);cursor:help}
tr.grp td{vertical-align:top}.lvl{font-weight:700;text-transform:capitalize}
.lvl.critical{color:var(--crit)}.lvl.high{color:var(--high)}.lvl.medium{color:var(--med)}.lvl.low,.lvl.informational{color:var(--low)}
h3{font-size:14px;text-transform:uppercase;letter-spacing:.06em;color:var(--muted);margin:22px 0 8px}
.muted{color:var(--muted)}.chain{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:20px;margin:22px 0}
.chips{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0}.chip{background:var(--chip);border-radius:999px;padding:2px 10px;font-size:13px}
.sev{color:var(--accent);font-weight:650}.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px;margin:14px 0}
.stat{border:1px solid var(--line);border-radius:10px;padding:10px 12px}.stat b{display:block;font-size:22px}
svg.graph{width:100%;height:auto;border:1px solid var(--line);border-radius:10px;background:var(--bg)}
.node rect{fill:var(--card);stroke-width:1.5}.node text{fill:var(--fg);font-size:12px}.node{cursor:pointer}
.node.source rect{stroke:var(--src)}.node.actor rect{stroke:var(--acct)}.node.host rect{stroke:var(--host)}
.edge path{fill:none;stroke:var(--muted);stroke-width:1.4;opacity:.7}.edge text{fill:var(--muted);font-size:10px;paint-order:stroke;stroke:var(--bg);stroke-width:4px;stroke-linejoin:round}
.coltitle{fill:var(--muted);font-size:11px;letter-spacing:.08em}.dim{opacity:.12!important}
.ev{display:grid;grid-template-columns:165px 1fr;gap:12px;padding:12px 0;border-top:1px solid var(--line)}
.ev b{display:block}.tag{font-size:11px;font-weight:700;border-radius:4px;padding:1px 6px;margin-left:6px;vertical-align:1px}
.tag.sequence{background:var(--seq);color:#fff}.tag.anomaly{border:1px solid var(--acct);color:var(--acct)}
code{font-size:12.5px;background:var(--chip);padding:1px 5px;border-radius:4px;word-break:break-all}
details{margin-top:6px}summary{cursor:pointer;color:var(--muted);font-size:13px}
pre{background:var(--chip);padding:10px;border-radius:8px;overflow:auto;font-size:12px;max-height:320px}
table{width:100%;border-collapse:collapse;font-size:13.5px}th,td{text-align:left;padding:6px 8px;border-top:1px solid var(--line)}
th{color:var(--muted);font-weight:600}.flag{color:var(--accent);font-weight:700}.tbl{overflow-x:auto}
@media (max-width:640px){.ev{grid-template-columns:1fr;gap:2px}}
"""

_JS = """
document.querySelectorAll('.chain').forEach(sec=>{
  const q=sec.querySelector('.f-text'),h=sec.querySelector('.f-host'),boxes=[...sec.querySelectorAll('.f-lvl')];
  if(!q)return;
  const apply=()=>{const lv=new Set(boxes.filter(b=>b.checked).map(b=>b.value)),t=q.value.toLowerCase(),hv=h.value;
    let n=0;sec.querySelectorAll('tr.grp').forEach(r=>{const ok=lv.has(r.dataset.level)&&(!hv||r.dataset.host===hv)&&
      (!t||r.dataset.text.includes(t));r.style.display=ok?'':'none';const d=r.nextElementSibling;if(d&&d.classList.contains('grp-d'))d.style.display=ok?'':'none';if(ok)n++;});
    sec.querySelector('.f-count').textContent=n+' alert groups shown';};
  [q,h,...boxes].forEach(x=>x.addEventListener('input',apply));apply();
});
document.querySelectorAll('svg.graph').forEach(svg=>{
  const sec=svg.closest('.chain');let active=null;
  svg.querySelectorAll('.node').forEach(n=>n.addEventListener('click',()=>{
    const k=n.dataset.key;active=active===k?null:k;
    sec.querySelectorAll('[data-keys]').forEach(el=>{
      const keys=el.dataset.keys.split('|');el.classList.toggle('dim',!!active&&!keys.includes(active));});
  }));
});
"""


def _graph(c: Chain, per_column: int = 10) -> str:
    e = html.escape
    cols = {"source": [], "actor": [], "host": []}
    labels: dict[str, str] = {}
    edges: dict[tuple[str, str], set[str]] = {}
    # big incidents: keep the highest-risk entities per column so the graph stays readable
    keep = {}
    for r in c.risk:
        kind = {"Account": "actor", "Source": "source", "Host": "host"}[r.kind]
        if sum(1 for k in keep.values() if k == kind) < per_column:
            keep[f"{kind}:{norm_entity(r.value, kind)}"] = kind

    def key(kind, v):
        k = f"{kind}:{norm_entity(v, kind)}"
        if k not in keep:
            return None
        if k not in labels:
            labels[k] = v
            cols[kind].append(k)
        return k

    for d in c.detections:
        if d.rule.kind == "sequence" or d.rule.level not in ALERT_LEVELS:
            continue
        s = key("source", d.source) if d.source else None
        a = key("actor", d.actor) if d.actor else None
        h = key("host", d.host) if d.host else None
        tech = ",".join(d.rule.attack_ids[:1]) or d.rule.title[:28]
        for x, y in ((s, a), (a, h)) if a else ((s, h),):
            if x and y:
                edges.setdefault((x, y), set()).add(tech)

    W, NW, NH, GAP, TOP = 960, 190, 30, 52, 44
    xs = {"source": 20, "actor": (W - NW) / 2, "host": W - NW - 20}
    rows = max((len(v) for v in cols.values()), default=1)
    H = TOP + rows * GAP + 10
    pos = {}
    for kind, ks in cols.items():
        offset = (rows - len(ks)) * GAP / 2
        for i, k in enumerate(ks):
            pos[k] = (xs[kind], TOP + offset + i * GAP)
    parts = [f"<svg class='graph' viewBox='0 0 {W} {H}' role='img' aria-label='Attack graph'>"]
    for kind, title in (("source", "SOURCES"), ("actor", "ACCOUNTS"), ("host", "HOSTS")):
        parts.append(f"<text class='coltitle' x='{xs[kind] + NW / 2}' y='22' text-anchor='middle'>{title}</text>")
    for (a, b), techs in edges.items():
        x1, y1 = pos[a][0] + NW, pos[a][1] + NH / 2
        x2, y2 = pos[b][0], pos[b][1] + NH / 2
        mx = (x1 + x2) / 2
        lbl = ", ".join(sorted(techs))
        parts.append(f"<g class='edge' data-keys='{e(a)}|{e(b)}'><title>{e(lbl)}</title>"
                     f"<path d='M{x1},{y1} C{mx},{y1} {mx},{y2} {x2},{y2}'/>"
                     f"<text x='{mx}' y='{(y1 + y2) / 2 - 4}' text-anchor='middle'>{e(lbl[:34])}</text></g>")
    neighbours: dict[str, set[str]] = {k: {k} for k in pos}
    for a, b in edges:
        neighbours[a].add(b)
        neighbours[b].add(a)
    for k, (x, y) in pos.items():
        kind = k.split(":", 1)[0]
        focus = "|".join(e(n) for n in sorted(neighbours[k]))
        full = labels[k]
        short = full.split("\\")[-1]
        if kind == "host" and not short.replace(".", "").isdigit():
            short = short.split(".")[0]
        short = short if len(short) <= 26 else short[:25] + "…"
        parts.append(f"<g class='node {kind}' data-key='{e(k)}' data-keys='{focus}'><title>{e(full)}</title>"
                     f"<rect x='{x}' y='{y}' width='{NW}' height='{NH}' rx='7'/>"
                     f"<text x='{x + 10}' y='{y + 19}'>{e(short)}</text></g>")
    parts.append("</svg>")
    return "".join(parts)


def _evjson(events: list[dict], limit=12) -> str:
    rows = [{k: (v.isoformat() if isinstance(v, datetime) else v) for k, v in ev.items()} for ev in events[:limit]]
    more = f"\n... {len(events) - limit} more" if len(events) > limit else ""
    return json.dumps(rows, indent=2, default=str) + more


def _alert_table(c: Chain, groups: list[AlertGroup], registry: dict[str, Rule]) -> str:
    e = html.escape
    hosts = sorted({short_host(g.host) for g in groups if g.host})
    levels = ["critical", "high", "medium", "low", "informational"]
    p = ["<div class='filters'><input type='search' class='f-text' placeholder='Search rule, host, account…'>"
         "<select class='f-host'><option value=''>All hosts</option>"
         + "".join(f"<option>{e(h)}</option>" for h in hosts) + "</select>"
         + "".join(f"<label><input type='checkbox' class='f-lvl' value='{l}' {'checked' if l in ALERT_LEVELS else ''}> "
                   f"{l}</label>" for l in levels)
         + "<span class='muted f-count'></span></div><div class='tbl'><table>"
         "<tr><th>First seen</th><th>Severity</th><th>Alert</th><th>Host</th><th>Count</th><th>Phase · ATT&amp;CK</th></tr>"]
    for g in groups:
        text = " ".join([g.rule.title, g.host, *g.actors, g.rule.meta.get("kill_chain", ""), *g.rule.attack_ids]).lower()
        tag = f" <span class='tag {g.rule.kind}'>{g.rule.kind.upper()}</span>" if g.rule.kind != "signature" else ""
        p.append(f"<tr class='grp' data-level='{e(g.level)}' data-host='{e(short_host(g.host))}' data-text='{e(text)}'>"
                 f"<td class='muted'>{e(g.first.strftime('%H:%M:%S'))}</td><td class='lvl {e(g.level)}'>{e(g.level)}</td>"
                 f"<td><b>{e(g.rule.title)}</b>{tag}<div class='muted'>{e(', '.join(show(a) for a in g.actors[:3]))}</div></td>"
                 f"<td>{e(short_host(g.host) or 'n/a')}</td><td>{g.count}"
                 + (f"<div class='muted'>until {e(g.last.strftime('%H:%M:%S'))}</div>" if g.count > 1 else "")
                 + f"</td><td>{e(g.rule.meta.get('kill_chain', ''))}<div class='muted'>{e(', '.join(g.rule.attack_ids[:3]))}</div></td></tr>")
        qs = _queries(g.detections[0], registry)
        body = f"<p>{e(g.rule.description)}</p>" if g.rule.description else ""
        if g.rule.kind == "sequence":
            d = g.detections[0]
            body += "<p class='muted'>" + " → ".join(f"{e(sid)} ({e(sd.time.strftime('%H:%M:%S'))})" for sid, sd in d.extra["steps"]) + "</p>"
        if qs:
            body += "<details><summary>Hunting queries</summary>" + "".join(
                f"<pre>{e(lang.upper())}\n{e(q)}</pre>" for lang, q in qs.items()) + "</details>"
        body += (f"<details><summary>Raw log events ({len(g.events)})</summary>"
                 f"<pre>{e(show(_evjson(g.events, 6)))}</pre></details>")
        p.append(f"<tr class='grp-d'><td></td><td colspan='5'><details><summary>Details, queries &amp; raw logs"
                 f"</summary>{body}</details></td></tr>")
    p.append("</table></div>")
    return "".join(p)


def html_report(chains: list[Chain], registry: dict[str, Rule], stats: dict | None = None,
                events: list[dict] | None = None, ai: dict[int, str] | None = None) -> str:
    e = html.escape
    stats = stats or {}
    pidx = process_index(events or [])
    p = [f"<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' "
         f"content='width=device-width,initial-scale=1'><title>ChainHunter Report</title><style>{_CSS}</style></head>"
         f"<body><main><h1>ChainHunter</h1><p class='muted'>Correlated attack chains · generated "
         f"{e(_ts(datetime.now(timezone.utc)))}</p><div class='stats'>"]
    for label, val in (("Events analysed", stats.get("events", "—")), ("Raw detections", stats.get("detections", "—")),
                       ("Sequences", stats.get("sequences", "—")), ("Anomalies", stats.get("anomalies", "—")),
                       ("Incidents", len(chains))):
        p.append(f"<div class='stat'><b>{e(f'{val:,}' if isinstance(val, int) else str(val))}</b>"
                 f"<span class='muted'>{label}</span></div>")
    p.append("</div>")
    for n, c in enumerate(chains, 1):
        groups = group_alerts(c)
        alerting = [g for g in groups if g.level in ALERT_LEVELS]
        hosts = sorted({short_host(h) for h in c.entities["hosts"]})
        p.append(f"<section class='chain'><h2>Incident {n} · <span class='sev'>{c.severity}</span> "
                 f"<span class='muted'>score {c.score:,}</span></h2><div class='muted'>{e(_ts(c.start))} → {e(_ts(c.end))} · "
                 f"confidence {e(c.confidence)} · {len(hosts)} host(s): {e(', '.join(hosts))} · "
                 f"{len(c.detections):,} detections in {len(groups)} alert groups ({len(alerting)} medium+)</div>"
                 f"<h3>Kill chain</h3><div class='chips'>")
        p += [f"<span class='chip'>{i + 1}. {e(ph)}</span>" for i, ph in enumerate(c.phases)]
        p.append("</div>")
        if ai and (n - 1) in ai:
            p.append(ai[n - 1])
        p.append("<h3>Alerts over time, by host <span class='muted' style='text-transform:none;letter-spacing:0'>"
                 "— hover a dot; dashed markers show where the intrusion reached a new host</span></h3>")
        p.append(swimlane(c))
        p.append("<div class='grid2'><div><h3>Entity graph <span class='muted' style='text-transform:none;"
                 "letter-spacing:0'>— click a node to focus</span></h3>")
        p.append(_graph(c))
        p.append("</div><div><h3>Entity risk (RBA)</h3><div class='tbl'><table><tr><th>Entity</th><th>Type</th>"
                 "<th>Risk</th><th>Techniques</th><th>Flag</th></tr>")
        for r in c.risk[:12]:
            techs = sorted(r.techniques)
            p.append(f"<tr><td><code>{e(show(r.value))}</code></td><td>{r.kind}</td><td>{r.score:,}</td>"
                     f"<td title='{e(', '.join(techs))}'>{len(techs)}</td>"
                     f"<td>{'<span class=flag>FLAGGED</span>' if r.flagged else ''}</td></tr>")
        p.append("</table></div></div></div>")
        tree = process_tree(c, pidx)
        if tree:
            p.append("<h3>Process tree <span class='muted' style='text-transform:none;letter-spacing:0'>"
                     "— rebuilt from Sysmon ProcessGuid lineage</span></h3>" + tree)
        p.append("<h3>Alert groups</h3>" + _alert_table(c, groups, registry))
        p.append("</section>")
    p.append(f"</main><script>{_JS}</script></body></html>")
    return "".join(p)


# ---------- ATT&CK Navigator layer ----------

def navigator_layer(chains: list[Chain], name: str = "ChainHunter detections") -> str:
    counts: dict[str, int] = {}
    for c in chains:
        for d in c.detections:
            for t in d.rule.attack_ids:
                counts[t] = counts.get(t, 0) + 1
    return json.dumps({
        "name": name, "versions": {"layer": "4.5", "navigator": "4.9.1", "attack": "15"},
        "domain": "enterprise-attack",
        "techniques": [{"techniqueID": t, "score": n, "comment": f"{n} detection(s)"} for t, n in sorted(counts.items())],
        "gradient": {"colors": ["#fde0dd", "#b4232a"], "minValue": 0, "maxValue": max(counts.values(), default=1)},
    }, indent=2)


def coverage_layer(rules: list[Rule]) -> str:
    techs = sorted({t for r in rules for t in r.attack_ids})
    return json.dumps({
        "name": "ChainHunter rule coverage", "versions": {"layer": "4.5", "navigator": "4.9.1", "attack": "15"},
        "domain": "enterprise-attack",
        "techniques": [{"techniqueID": t, "score": 1, "color": "#1f5fa8",
                        "comment": ", ".join(r.id for r in rules if t in r.attack_ids)} for t in techs],
    }, indent=2)


# ---------- JSON (SOAR hand-off) ----------

def json_export(chains: list[Chain]) -> str:
    def det(d: Detection):
        return {"rule_id": d.rule.id, "title": d.rule.title, "kind": d.rule.kind, "level": d.rule.level,
                "start": d.time.isoformat(), "end": d.end.isoformat(), "actor": d.actor, "host": d.host,
                "source": d.source, "attack": d.rule.attack_ids, "kill_chain": d.rule.meta.get("kill_chain"),
                "event_count": len(d.events), "risk": risk_of(d)}
    return json.dumps([{
        "incident": i, "severity": c.severity, "score": c.score, "confidence": c.confidence,
        "start": c.start.isoformat(), "end": c.end.isoformat(), "phases": c.phases, "techniques": c.techniques,
        "entities": {k: sorted(v) for k, v in c.entities.items()},
        "entity_risk": [{"type": r.kind, "value": r.value, "score": r.score, "flagged": r.flagged,
                         "techniques": sorted(r.techniques)} for r in c.risk],
        "detections": [det(d) for d in c.detections],
    } for i, c in enumerate(chains, 1)], indent=2)
